# Generated by Django 4.2.5 on 2025-02-26 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_code', models.CharField(max_length=7, unique=True, verbose_name='プロモーションコード')),
                ('discount', models.IntegerField(verbose_name='割引額')),
                ('is_used', models.BooleanField(default=False, verbose_name='使用済み判定')),
                ('used_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='使用日時')),
            ],
            options={
                'db_table': 'promotion_code',
            },
        ),
    ]
