# Generated by Django 4.2.5 on 2025-02-27 13:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('promotion_code', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotioncode',
            name='used_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='使用日時'),
        ),
    ]
