# Generated by Django 4.2.5 on 2025-02-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_session_id_alter_cartproduct_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='session_id',
            field=models.CharField(default='temp_session_id', max_length=32, unique=True),
        ),
    ]
