# Generated by Django 4.2.5 on 2025-02-11 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20250207_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_purchased',
        ),
    ]
