# Generated by Django 4.2.5 on 2025-02-27 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotion_code', '0002_alter_promotioncode_used_at'),
        ('cart', '0005_remove_cart_is_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='promo_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='promotion_code.promotioncode', verbose_name='プロモーションコードID'),
        ),
    ]
