# Generated by Django 4.2.5 on 2025-03-01 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_cart_promo_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='promo_code',
        ),
    ]
