# Generated by Django 4.2.5 on 2025-02-06 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0002_alter_cart_session_id_alter_cartproduct_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(verbose_name='姓')),
                ('first_name', models.CharField(verbose_name='名')),
                ('username', models.CharField(unique=True, verbose_name='ユーザー名')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='メールアドレス')),
                ('country', models.CharField(verbose_name='国')),
                ('state_prefecture', models.CharField(verbose_name='州/県')),
                ('zip', models.CharField(max_length=9, verbose_name='郵便番号')),
                ('address1', models.CharField(max_length=255, verbose_name='住所1')),
                ('address2', models.CharField(blank=True, max_length=255, null=True, verbose_name='住所2')),
                ('same_address', models.BooleanField(default=False, verbose_name='請求先と配送先が同じ')),
                ('next_save', models.BooleanField(default=False, verbose_name='配送先住所を保存')),
            ],
            options={
                'db_table': 'billing_address',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_holder', models.CharField(verbose_name='カード名義')),
                ('card_number_hash', models.CharField(max_length=255, verbose_name='カード番号（暗号化）')),
                ('card_last4', models.CharField(max_length=4, verbose_name='カード下4桁')),
                ('expiration_date', models.CharField(max_length=7, verbose_name='有効期限')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.billingaddress', verbose_name='配送先ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_cart', to='cart.cart', verbose_name='カートID')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.payment', verbose_name='支払いID')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
