# Generated by Django 4.2.5 on 2025-02-16 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_order_id_orderitem_order_remove_order_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_address', to='order.billingaddress', verbose_name='配送先ID'),
        ),
    ]
