# Generated by Django 4.2.5 on 2025-01-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='product_images', verbose_name='商品画像'),
        ),
    ]
